name: Pantheon WP EI Build
on:
  push:
    branches:
      - build
jobs:
  test:
    runs-on: ubuntu-latest
    name: Install composer dependencies and run tests
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Run lint
      run: composer lint
    - name: Run unit tests
      run: composer test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile assets
      run: |
        npm install
        npm run build
    - name: Commit and push build files
      run: |
        git config --local user.email "bot@getpantheon.com"
        git config --local user.name "Pantheon Automation"
        git add -f dist/
        git commit -m "Built assets"
