name: Pantheon WordPress Edge Integrations
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies and run tests
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install

    - name: Run lint
      run: composer lint

    - name: Run unit tests
      run: composer test
