name: Pantheon WP EI Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Populate changelog. Could be done on release instead.
    # Source: https://github.com/johnbillion/user-switching/blob/develop/.github/workflows/deploy-tag.yml
    # - name: Install Dependencies
    #   run: npm install

    # - name: Populate Changelog
    #   run: node .github/workflows/changelog.js README.md
    #   env:
    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: WordPress Plugin Deploy
    #   uses: 10up/action-wordpress-plugin-deploy@1.4.1
    #   env:
    #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
